### ISSUE TITLE
build on Linux?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [EricBishton/Flaxe#1]
Thanks to point me out of how to build Flaxe on linux

**Comment by EricBishton** [comment]
Sorry, I didn't see this sooner.  This product has a gradle build script associated with it.  Building on Linux is (should be) as simple as running `gradlew assemble` as the README says.  

As a prerequisite, you will have to install gradle, of course.  I build it using the version installed with IntelliJ IDEA.

**Comment by EricBishton** [comment]
More specifically, for Ubuntu:
1) Download the repository and change to the project root directory.
2) Install gradle:  `$ sudo apt install gradle`
2a) Set up gradle:  `$ sudo gradle wrapper`
3) Change `./gradlew` permissions: `$ sudo chmod 755 ./gradlew`
4) Make sure that java *8* is installed.  (Gradle dependency)
4a) `$ sudo apt install openjdk-8-jdk`
4b) `$ sudo update-alternatives java`; select openjdk 8 -- probably `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`
5) Run the build step:  `$ ./gradlew assemble`
`flaxe.jar` will be in `.../build/lib/flaxe.jar`

Let me know if this doesn't work for you.
